name: Verify Rancher Connection

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  verify-connection:
    runs-on: ubuntu-latest
    
    env:
      RANCHER_ACCESS_KEY: ${{ secrets.RANCHER_ACCESS_KEY }}
      RANCHER_SECRET_KEY: ${{ secrets.RANCHER_SECRET_KEY }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Install kubectl
        run: |
          curl -LO "https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl"
          chmod +x kubectl
          sudo mv kubectl /usr/local/bin/
          
      - name: Verify Rancher Connection
        run: |
          # Run Rancher CLI in a Docker container
          docker run -e RANCHER_ACCESS_KEY=${{ secrets.RANCHER_ACCESS_KEY }} \
                     -e RANCHER_SECRET_KEY=${{ secrets.RANCHER_SECRET_KEY }} \
                     rancher/cli:v2.6.11 \
                     rancher login --token $RANCHER_ACCESS_KEY:$RANCHER_SECRET_KEY https://192.168.1.230/
          
          # Verify connection by getting cluster information
          docker run -e RANCHER_ACCESS_KEY=${{ secrets.RANCHER_ACCESS_KEY }} \
                     -e RANCHER_SECRET_KEY=${{ secrets.RANCHER_SECRET_KEY }} \
                     rancher/cli:v2.6.11 \
                     rancher context switch local
          
          docker run -e RANCHER_ACCESS_KEY=${{ secrets.RANCHER_ACCESS_KEY }} \
                     -e RANCHER_SECRET_KEY=${{ secrets.RANCHER_SECRET_KEY }} \
                     rancher/cli:v2.6.11 \
                     kubectl get nodes
