name: Verify Rancher Connection

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  verify-connection:
    runs-on: ubuntu-latest
    
    env:
      RANCHER_ACCESS_KEY: ${{ secrets.RANCHER_ACCESS_KEY }}
      RANCHER_SECRET_KEY: ${{ secrets.RANCHER_SECRET_KEY }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Install kubectl
        run: |
          curl -LO "https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl"
          chmod +x kubectl
          sudo mv kubectl /usr/local/bin/
          
      - name: Verify Rancher Connection and Get Nodes
        run: |
          docker run -v $HOME/.kube:/root/.kube --rm \
            docker --version \
            -e RANCHER_URL=https://192.168.1.230/ \
            -e RANCHER_ACCESS_KEY=${{ secrets.RANCHER_ACCESS_KEY }} \
            -e RANCHER_SECRET_KEY=${{ secrets.RANCHER_SECRET_KEY }} \
            rancher/cli:v2.4.10 \
            rancher context switch local && kubectl get nodes
