name: Verify Rancher Connection

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  verify-connection:
    runs-on: ubuntu-latest
    
    env:
      RANCHER_ACCESS_KEY: ${{ secrets.RANCHER_ACCESS_KEY }}
      RANCHER_SECRET_KEY: ${{ secrets.RANCHER_SECRET_KEY }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Install kubectl
        run: |
          curl -LO "https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl"
          chmod +x kubectl
          sudo mv kubectl /usr/local/bin/
          
      - name: Install Rancher CLI
        run: |
          # Download and install Rancher CLI
          curl -LO "https://github.com/rancher/cli/releases/download/v2.6.11/rancher-linux-amd64"
          chmod +x rancher-linux-amd64
          sudo mv rancher-linux-amd64 /usr/local/bin/rancher  
          
      - name: Verify Rancher Connection
        run: |
          # Authenticate with Rancher using API tokens
          rancher login --token $RANCHER_ACCESS_KEY:$RANCHER_SECRET_KEY https://192.168.1.230/
          
          # Verify connection by getting cluster information
          rancher context switch local
          kubectl get nodes
